language: node_js
node_js:
  - 10

addons:
  chrome: stable

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install
  - cd ./server && npm install && cd ../
script:
  - yarn all_tests
  - cd ./server && npm run test && cd ../

after_success:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive


