language: node_js
node_js:
  - 10

addons:
  chrome: stable

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install
script:
  - npm test

after_success:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive


