language: node_js
node_js:
  - 10

addons:
  chrome: stable

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install
  - cd ./functions && npm install && cd ../
script:
  - npm test




